# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  buildConfiguration: 'Release'
  version: '1.0.0'

steps:
- task: DotNetCoreInstaller@0
  displayName: 'Use .NET Core SDK Tool Installer'
  inputs:
    version: 2.2.100
- script: dotnet build src/ApplicationInsights.Extension.RequestLogging.sln --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
- script: dotnet pack src/ApplicationInsights.Extension.RequestLogging/ApplicationInsights.Extension.RequestLogging.csproj --configuration $(buildConfiguration) /p:PackageVersion=$(version)
- task: NuGetCommand@2
  inputs:
    command: push
    nuGetFeedType: external
    publishFeedCredentials: 'Nuget-ApplicationInsights.Extension.RequestLogging'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg'
    versioningScheme: byEnvVar
    versionEnvVar: version